
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
rplotsOptions <- R6::R6Class(
    "rplotsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            splitBy = NULL,
            violin = TRUE,
            boxplot = TRUE,
            jitter = FALSE, ...) {

            super$initialize(
                package='walrus',
                name='rplots',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..splitBy <- jmvcore::OptionVariable$new(
                "splitBy",
                splitBy,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "nominal",
                    "ordinal",
                    "nominaltext"))
            private$..violin <- jmvcore::OptionBool$new(
                "violin",
                violin,
                default=TRUE)
            private$..boxplot <- jmvcore::OptionBool$new(
                "boxplot",
                boxplot,
                default=TRUE)
            private$..jitter <- jmvcore::OptionBool$new(
                "jitter",
                jitter,
                default=FALSE)
        
            self$.addOption(private$..vars)
            self$.addOption(private$..splitBy)
            self$.addOption(private$..violin)
            self$.addOption(private$..boxplot)
            self$.addOption(private$..jitter)
        }),
    active = list(
        vars = function() private$..vars$value,
        splitBy = function() private$..splitBy$value,
        violin = function() private$..violin$value,
        boxplot = function() private$..boxplot$value,
        jitter = function() private$..jitter$value),
    private = list(
        ..vars = NA,
        ..splitBy = NA,
        ..violin = NA,
        ..boxplot = NA,
        ..jitter = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
rplotsResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plots = function() private$..plots),
    private = list(
        ..plots = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Box & Violin Plots")
            private$..plots <- jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(vars)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderFun=".plot",
                    clearWith=list(
                        "splitBy",
                        "violin",
                        "boxplot",
                        "jitter")))
            self$add(private$..plots)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
rplotsBase <- R6::R6Class(
    "rplotsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'walrus',
                name = 'rplots',
                version = c(1,0,0),
                options = options,
                results = rplotsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Box & Violin Plots
#'
#' 
#' @param data .
#' @param vars .
#' @param splitBy .
#' @param violin .
#' @param boxplot .
#' @param jitter .
#' @export
rplots <- function(
    data,
    vars,
    splitBy,
    violin = TRUE,
    boxplot = TRUE,
    jitter = FALSE) {

    options <- rplotsOptions$new(
        vars = vars,
        splitBy = splitBy,
        violin = violin,
        boxplot = boxplot,
        jitter = jitter)

    results <- rplotsResults$new(
        options = options)

    analysis <- rplotsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
